services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 16052002Ad@m
      MYSQL_ROOT_PASSWORD: 16052002Ad@m
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    volumes:
      - $HOME/nodeapp:/code
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 16052002Ad@m
      DB_NAME: db
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 3000
    depends_on:
      - mysqldb
    networks:
      - internalnet

  front:
    container_name: frontcontainer
    image: anatholyb/killer-bee-front:v1.0.5
    environment:
      SERVICE_TAGS: prod
      SERVICE_NAME: front
    networks:
      - internalnet

  nginx:
      build: ./nginx
      container_name: nginxcontainer  
      ports:
        - "80:80"
      depends_on:
        - front
        - nodeapp
      restart: always
      networks:
        - internalnet

networks:
  internalnet:
    driver: bridge